spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test2?serverTimezone=Asia/Seoul
    username: root
    password: 1234
    properties:
      hibernate:
        default_batch_fetch_size: 100
  config:
    import: application-oauth.yml
  jpa:
    hibernate:
      ddl-auto: create
      database-platform: org.hibernate.dialect.MySQL8Dialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    generate-ddl: true



jwt:
  secretKey: asdasdasdasdasdadadadadadadadadadadadafafafafasfasfasfasfafafafs
  access:
    expiration: 200000000000 # 1시간(60분) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h)) 1000 * 200
    header: Authorization

  refresh:
    expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
    header: Authorizationrefresh