spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://campuscrew.ccibsmzxsm8j.us-east-1.rds.amazonaws.com:3306/test9?serverTimezone=Asia/Seoul
    username: admin
    password: ch359415
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        default_batch_fetch_size: 100
  config:
    import: application-oauth.yml

jwt:
  secretKey: asdasdasdasdasdadadadadadadadadadadadafafafafasfasfasfasfafafafs
  access:
    expiration: 200000000000 # 1시간(60분) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h)) 1000 * 200
    header: Authorization

  refresh:
    expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
    header: Authorizationrefresh