package com.campuscrew.campuscrew;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.servlet.config.annotation.CorsRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;

@SpringBootApplication
public class CampuscrewApplication {
	public static void main(String[] args) {
		SpringApplication.run(CampuscrewApplication.class, args);
	}
}
//eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImV4cCI6MTY3OTU0ODIxMCwiZW1haWwiOiJkNzY2MTgzNC02N2I0LTQ4YTItYTRhOS0xMzc3NWQzZmNmOGJAZ29vZ2xlLmNvbSJ9.0gA5d5zMCnbEZll8Q4PS1NM9fHtePW8ISrnfMXaSvlwWuH7iLGNfEkwMBf1Ym2mzxaYFOM8a-skCW3iBARgJBA

//eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImV4cCI6MTY3OTU0ODIzMCwiZW1haWwiOiJkNzY2MTgzNC02N2I0LTQ4YTItYTRhOS0xMzc3NWQzZmNmOGJAZ29vZ2xlLmNvbSJ9.vLFUL6HR1_-GWTe8kwcRulfCvfMJOgzoTkN9ZFAhKK8-1b0t0zPP72sd6S9p0tJIVUe1EEEjcp1Cdw76bhEAmw